name: zenity-part
version: current
summary: Display a simple dialog for your snap
description: |
  This remote part features a build of the zenity dialog program, for depending part to display a dialog like snap deprecation, etc.

  Refer the following forum topic for more info:

    The Zenity Remote Part - doc - snapcraft.io
    https://forum.snapcraft.io/t/the-zenity-remote-part/8793

grade: stable
confinement: strict

apps:
  zenity-part:
    command: >
      desktop-launch
      zenity

  greeting:
    command: >
      desktop-launch
      zenity
        --info
        --text='Hello Zenity from a snap!'
        --width=600

  obsoletion-notice:
    command: >
      desktop-launch
      zenity
        --warning
        --text='This snap has now been <b>superseded</b> and will NOT receive any further updates!  Please remove this snap and install the \`_snap_name_\` snap as soon as possible!'
        --width=600

plugs:
  desktop:
  desktop-legacy:
  unity7:
  wayland:
  x11:

parts:
  desktop-gtk3:

  zenity:
    source: https://gitlab.gnome.org/GNOME/zenity.git
    source-tag: 3.28.1
    source-depth: 1
    plugin: autotools
    configflags:
    - --datarootdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/share
    - --disable-libnotify
    - --disable-webkitgtk
    build-packages:
    - gnome-pkg-tools
    - gnome-common
    - yelp-tools
    - gettext
    - libglib2.0-dev
    - libgtk-3-dev
    override-build: |
      set \
        -o errexit \
        -o nounset

      snapcraftctl build

    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current: /
